version: "3.7"

services:
    database:
        image: mysql:5.7 
        environment:
            MYSQL_DATABASE: bookstore_db
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_USER: tulay
            MYSQL_PASSWORD: tulay_1 
        networks:
            - clarusnet    
    my-app: 
        image: tulay/bookstore-api:latest 
        restart: always
        depend_on:
            - database
        ports:
            - "80:80" 
networks:
    clarusnet:
        driver: bridge                
            
        